

# ___Text Analytics in Python___

#### Introduction

Text data has been one of the most important sources across areas. In this notebook, we will use a toy dataset to go though a common text analytics procedure in Python.

## Let's take a simple example

In [ ]:
import pandas as pd

time_sentences = ["Monday: The doctor's appointment is at 2:45pm to check cancer status.",
                  "Tuesday: The dentist's appointment is at 11:30 am.",
                  "Wednesday: At 7:00pm, there is a basketball game!",
                  "Thursday: Be back home by 11:15 pm at the latest.",
                  "Friday: Take the train at 08:10 am, arrive at 09:00am."]

df = pd.DataFrame(time_sentences, columns=['text'])
df

                                                text
0  Monday: The doctor's appointment is at 2:45pm ...
1  Tuesday: The dentist's appointment is at 11:30...
2  Wednesday: At 7:00pm, there is a basketball game!
3  Thursday: Be back home by 11:15 pm at the latest.
4  Friday: Take the train at 08:10 am, arrive at ...

In [ ]:
# find the number of characters for each string in df['text']
df['text'].str.len()

0    69
1    50
2    49
3    49
4    54
Name: text, dtype: int64

In [ ]:
# find the number of tokens for each string in df['text']
df['text'].str.split().str.len()

0    11
1     8
2     8
3    10
4    10
Name: text, dtype: int64

In [ ]:
# find which entries contain the word 'cancer'
df['text'].str.contains('cancer')

0     True
1    False
2    False
3    False
4    False
Name: text, dtype: bool

In [ ]:
# find how many times a digit occurs in each string
df['text'].str.count(r'\d')

0    3
1    4
2    3
3    4
4    8
Name: text, dtype: int64

In [ ]:
# find all occurances of the digits
df['text'].str.findall(r'\d')

0                   [2, 4, 5]
1                [1, 1, 3, 0]
2                   [7, 0, 0]
3                [1, 1, 1, 5]
4    [0, 8, 1, 0, 0, 9, 0, 0]
Name: text, dtype: object

In [ ]:
# group and find the hours and minutes
df['text'].str.findall(r'(\d?\d):(\d\d)')

0               [(2, 45)]
1              [(11, 30)]
2               [(7, 00)]
3              [(11, 15)]
4    [(08, 10), (09, 00)]
Name: text, dtype: object

In [ ]:
# replace weekdays with '???'
df['text'].str.replace(r'\w+day\b', '???')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

0    ???: The doctor's appointment is at 2:45pm to ...
1       ???: The dentist's appointment is at 11:30 am.
2          ???: At 7:00pm, there is a basketball game!
3         ???: Be back home by 11:15 pm at the latest.
4    ???: Take the train at 08:10 am, arrive at 09:...
Name: text, dtype: object

In [ ]:
# replace weekdays with 3 letter abbrevations
df['text'].str.replace(r'(\w+day\b)', lambda x: x.groups()[0][:3])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

0    Mon: The doctor's appointment is at 2:45pm to ...
1       Tue: The dentist's appointment is at 11:30 am.
2          Wed: At 7:00pm, there is a basketball game!
3         Thu: Be back home by 11:15 pm at the latest.
4    Fri: Take the train at 08:10 am, arrive at 09:...
Name: text, dtype: object

In [ ]:
# create new columns from first match of extracted groups
df['text'].str.extract(r'(\d?\d):(\d\d)')

    0   1
0   2  45
1  11  30
2   7  00
3  11  15
4  08  10

In [ ]:
# extract the entire time, the hours, the minutes, and the period
df['text'].str.extractall(r'((\d?\d):(\d\d) ?([ap]m))')

                0   1   2   3
  match
0 0        2:45pm   2  45  pm
1 0      11:30 am  11  30  am
2 0        7:00pm   7  00  pm
3 0      11:15 pm  11  15  pm
4 0      08:10 am  08  10  am
  1       09:00am  09  00  am

In [ ]:
# extract the entire time, the hours, the minutes, and the period with group names
df['text'].str.extractall(r'(?P<time>(?P<hour>\d?\d):(?P<minute>\d\d) ?(?P<period>[ap]m))')

             time hour minute period
  match
0 0        2:45pm    2     45     pm
1 0      11:30 am   11     30     am
2 0        7:00pm    7     00     pm
3 0      11:15 pm   11     15     pm
4 0      08:10 am   08     10     am
  1       09:00am   09     00     am

## Let's talk more on real data

In [1]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
import os
os.chdir('/content/gdrive/My Drive/Teaching-task/python-DS')
!pwd

In [ ]:
df = pd.read_csv('./sample-data/ag_news.csv')
df.head()

,class_index,title,description,class_name
0,3,Fears for T N pension after talks,Unions representing workers at Turner Newall...,Business
1,4,The Race is On: Second Private Team Sets Launc...,"SPACE.com - TORONTO, Canada -- A second\team o...",Sci/Tech
2,4,Ky. Company Wins Grant to Study Peptides (AP),AP - A company founded by a chemistry research...,Sci/Tech
3,4,Prediction Unit Helps Forecast Wildfires (AP),AP - It's barely dawn when Mike Fitzpatrick st...,Sci/Tech
4,4,Calif. Aims to Limit Farm-Related Smog (AP),AP - Southern California's smog-fighting agenc...,Sci/Tech

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7600 entries, 0 to 7599
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class_index  7600 non-null   int64
 1   title        7600 non-null   object
 2   description  7600 non-null   object
 3   class_name   7600 non-null   object
dtypes: int64(1), object(3)
memory usage: 237.6+ KB

In [ ]:
set(df['class_name'].values)

{'Business', 'Sci/Tech', 'Sports', 'World'}

There are four columns:
- class index and class names that annotate the content type
- title and description of each news piece

Let's combine the title and description into a column called `content` and drop unneccessary columns.

In [ ]:
df['content'] = df['title'] + '. ' + df['description']
df.drop(columns=['title', 'description'], inplace=True)
df.head(5)

   class_index class_name                                            content
0            3   Business  Fears for T N pension after talks. Unions repr...
1            4   Sci/Tech  The Race is On: Second Private Team Sets Launc...
2            4   Sci/Tech  Ky. Company Wins Grant to Study Peptides (AP)....
3            4   Sci/Tech  Prediction Unit Helps Forecast Wildfires (AP)....
4            4   Sci/Tech  Calif. Aims to Limit Farm-Related Smog (AP). A...

---

#### Document Representation

While we as human can understand the text, machines can hardly know text as it is. A classic way to mathematically represent text data is to convert them into [vector spaces](https://en.wikipedia.org/wiki/Vector_space_model). Specifically, each document will be stored as a vector, where each element is a ___weight___ for one term. A simple and commonly used approach is to tokenize documents and use term frequencies or [term frequency-inverse document frequency (TFIDF)](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) as weights.

##### Bag-of-Words (BOW)

While more sophisticated approaches are available, BOW representation is still very popular due to its simplicity. In this style, we can forget word orders and treat each document as ___a bag of words___. While this is a very strong assumption, it still makes sense -- we can understand a sentence even if the words are randomly ordered. For example, we can easily understand the following sentence:

> sitting a chair is cat there on

In Python, we can use a `numpy.ndarray` or `list` to save this information:

In [ ]:
sentence = ['stting', 'a', 'chair', 'is', 'cat', 'there', 'on']
sentence

['stting', 'a', 'chair', 'is', 'cat', 'there', 'on']

###### Tokenize

Let's now apply this onto our toy dataset. In English text (and many other languages), we can simply split each document by spaces. Besides, we usually may want to remove puncutations because they do not provide valuable information. Last but not least, we may want to exclude some very common words (e.g., `the`, `we`, `you`, `is`, etc.), called [___stop words___](https://en.wikipedia.org/wiki/Stop_words).

In [ ]:
from string import punctuation
print(punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

If there's no special needs, we can simply use a common stop word list from `nltk`.

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
from nltk.corpus import stopwords
eng_stopwords = stopwords.words('english')
eng_stopwords[:20]

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his']

Now we can start to convert the contents into bag of words! To do this, we may utilize the package [`nltk`'s tokenize package](http://www.nltk.org/api/nltk.tokenize.html)

In [ ]:
import nltk

In [ ]:
df.head(8)

   class_index class_name                                            content
0            3   Business  Fears for T N pension after talks. Unions repr...
1            4   Sci/Tech  The Race is On: Second Private Team Sets Launc...
2            4   Sci/Tech  Ky. Company Wins Grant to Study Peptides (AP)....
3            4   Sci/Tech  Prediction Unit Helps Forecast Wildfires (AP)....
4            4   Sci/Tech  Calif. Aims to Limit Farm-Related Smog (AP). A...
5            4   Sci/Tech  Open Letter Against British Copyright Indoctri...
6            4   Sci/Tech  Loosing the War on Terrorism. \\"Sven Jaschan,...
7            4   Sci/Tech  FOAFKey: FOAF, PGP, Key Distribution, and Bloo...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7600 entries, 0 to 7599
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   class_index  7600 non-null   int64
 1   class_name   7600 non-null   object
 2   content      7600 non-null   object
dtypes: int64(1), object(2)
memory usage: 178.2+ KB

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
# also convert them to lower case
bow = [nltk.word_tokenize(content.lower()) for content in df['content'].values]
# show the first 1
print('; '.join(bow[0]))

fears; for; t; n; pension; after; talks; .; unions; representing; workers; at; turner; newall; say; they; are; 'disappointed; '; after; talks; with; stricken; parent; firm; federal; mogul; .

In [ ]:
len(bow)

7600

In [ ]:
bow[0]

['fears',
 'for',
 't',
 'n',
 'pension',
 'after',
 'talks',
 '.',
 'unions',
 'representing',
 'workers',
 'at',
 'turner',
 'newall',
 'say',
 'they',
 'are',
 "'disappointed",
 "'",
 'after',
 'talks',
 'with',
 'stricken',
 'parent',
 'firm',
 'federal',
 'mogul',
 '.']

In [ ]:
bow[1]

['the',
 'race',
 'is',
 'on',
 ':',
 'second',
 'private',
 'team',
 'sets',
 'launch',
 'date',
 'for',
 'human',
 'spaceflight',
 '(',
 'space.com',
 ')',
 '.',
 'space.com',
 '-',
 'toronto',
 ',',
 'canada',
 '--',
 'a',
 'second\\team',
 'of',
 'rocketeers',
 'competing',
 'for',
 'the',
 '#',
 '36',
 ';',
 '10',
 'million',
 'ansari',
 'x',
 'prize',
 ',',
 'a',
 'contest',
 'for\\privately',
 'funded',
 'suborbital',
 'space',
 'flight',
 ',',
 'has',
 'officially',
 'announced',
 'the',
 'first\\launch',
 'date',
 'for',
 'its',
 'manned',
 'rocket',
 '.']

Let's remove the stop words and punctuations. Note that there are some very short words of length 1. I will typically remove them as well if they do not have special meanings. Also, I will remove pure numbers by `str.isdigit`. Note that this may not work well but for simplicity, we will just go with it. See more dicussion on this issue [here](https://stackoverflow.com/questions/354038/how-do-i-check-if-a-string-is-a-number-float?page=1&tab=votes#tab-top).

In [ ]:
min_length = 3 # define the customized minimum length

In [ ]:
bow = [[word for word in content if word not in punctuation and word not in eng_stopwords and not word.isdigit()] for content in bow]
print('; '.join(bow[0]))

fears; n; pension; talks; unions; representing; workers; turner; newall; say; 'disappointed; talks; stricken; parent; firm; federal; mogul

In [ ]:
print('; '.join(bow[1]))

race; second; private; team; sets; launch; date; human; spaceflight; space.com; space.com; toronto; canada; --; second\team; rocketeers; competing; million; ansari; x; prize; contest; for\privately; funded; suborbital; space; flight; officially; announced; first\launch; date; manned; rocket

As we can, sometimes we need further data cleaning to remove punctuations in words. In this example, we want to remove the quote in the word "disappointed". In this case, we can utilize [`string.translate`](https://stackoverflow.com/questions/34293875/how-to-remove-punctuation-marks-from-a-string-in-python-3-x-using-translate):

In [ ]:
# do not translate anything, except for removing all punctuations
trans = str.maketrans('', '', punctuation)
bow = [[w.translate(trans).strip() for w in d] for d in bow]
bow = [[w for w in d if len(w) >= min_length] for d in bow]
print('; '.join(bow[0]))

fears; pension; talks; unions; representing; workers; turner; newall; say; disappointed; talks; stricken; parent; firm; federal; mogul

In [ ]:
for i in range(1, 5):
    print('; '.join(bow[i]))
    print('---------------'*10)

race; second; private; team; sets; launch; date; human; spaceflight; spacecom; spacecom; toronto; canada; secondteam; rocketeers; competing; million; ansari; prize; contest; forprivately; funded; suborbital; space; flight; officially; announced; firstlaunch; date; manned; rocket
------------------------------------------------------------------------------------------------------------------------------------------------------
company; wins; grant; study; peptides; company; founded; chemistry; researcher; university; louisville; grant; develop; method; producing; better; peptides; short; chains; amino; acids; building; blocks; proteins
------------------------------------------------------------------------------------------------------------------------------------------------------
prediction; unit; helps; forecast; wildfires; barely; dawn; mike; fitzpatrick; starts; shift; blur; colorful; maps; figures; endless; charts; already; knows; day; bring; lightning; strike; places; expects; winds; pick; moist; places; dry; flames; roar
------------------------------------------------------------------------------------------------------------------------------------------------------
calif; aims; limit; farmrelated; smog; southern; california; smogfighting; agency; went; emissions; bovine; variety; friday; adopting; nation; first; rules; reduce; air; pollution; dairy; cow; manure
------------------------------------------------------------------------------------------------------------------------------------------------------

###### Stemming/Lemmetization

Finally, it is noteworthy that one word can take different forms. For example, run can be ___run___, ___runs___, ___ran___, and ___running___. While they are different, they mean the same thing. There are two common methods to reduce a word back to the root form.

The first one is called ___stemming___, where each word will bee reduced to its "stem". For example, the stem of the word ___fly___ will be ___fli___

In [ ]:
from nltk import PorterStemmer
stemmer = PorterStemmer()
for w in ['fly', 'papers', 'communication', 'community']:
    print(w, ': ', stemmer.stem(w))

fly :  fli
papers :  paper
communication :  commun
community :  commun

While this seems to be okay, sometimes it is hard to ___reverse___ the stemming result (e.g., both "communication" and "community" are transformed to "commun", although they mean very different things). A second choice can be ___lemmatization___, which makes a word to its [___lemma__ ](https://en.wikipedia.org/wiki/Lemma_(morphology)), or say canonical or dictionary form.

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
from nltk import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
for w in ['flies', 'papers', 'communication', 'communities']:
    print(w, ': ', lemmatizer.lemmatize(w))

flies :  fly
papers :  paper
communication :  communication
communities :  community

For simplicity, let's just use stemming.

In [ ]:
bow = [[stemmer.stem(w) for w in d] for d in bow]

In [ ]:
for i in range(1, 5):
    print('; '.join(bow[i]))
    print('---------------'*10)

race; second; privat; team; set; launch; date; human; spaceflight; spacecom; spacecom; toronto; canada; secondteam; rocket; compet; million; ansari; prize; contest; forpriv; fund; suborbit; space; flight; offici; announc; firstlaunch; date; man; rocket
------------------------------------------------------------------------------------------------------------------------------------------------------
compani; win; grant; studi; peptid; compani; found; chemistri; research; univers; louisvil; grant; develop; method; produc; better; peptid; short; chain; amino; acid; build; block; protein
------------------------------------------------------------------------------------------------------------------------------------------------------
predict; unit; help; forecast; wildfir; bare; dawn; mike; fitzpatrick; start; shift; blur; color; map; figur; endless; chart; alreadi; know; day; bring; lightn; strike; place; expect; wind; pick; moist; place; dri; flame; roar
------------------------------------------------------------------------------------------------------------------------------------------------------
calif; aim; limit; farmrel; smog; southern; california; smogfight; agenc; went; emiss; bovin; varieti; friday; adopt; nation; first; rule; reduc; air; pollut; dairi; cow; manur
------------------------------------------------------------------------------------------------------------------------------------------------------

##### Vector Space Model (VSM)

Now that we have a bag of words, we can create vectors based on these items. Instead of using tokens/text, it is easier and better to just use integer indices. For example, `race` is the first word and therefore the number `1` maps to `race`.

For this task, the best approach may be [`gensim`](https://radimrehurek.com/gensim/index.html), which has a library of very well written and convenient APIs, especially for [topic modeling](https://en.wikipedia.org/wiki/Topic_model) and [word2vec](https://rare-technologies.com/word2vec-tutorial/) algorithms:

In [ ]:
import gensim
dictionary = gensim.corpora.Dictionary(bow)
print(dictionary)

Dictionary(17957 unique tokens: ['disappoint', 'fear', 'feder', 'firm', 'mogul']...)

In [ ]:
gensim.__version__

'3.6.0'

In [ ]:
dictionary.token2id

{'disappoint': 0,
 'fear': 1,
 'feder': 2,
 'firm': 3,
 'mogul': 4,
 'newal': 5,
 'parent': 6,
 'pension': 7,
 'repres': 8,
 'say': 9,
 'stricken': 10,
 'talk': 11,
 'turner': 12,
 'union': 13,
 'worker': 14,
 'announc': 15,
 'ansari': 16,
 'canada': 17,
 'compet': 18,
 'contest': 19,
 'date': 20,
 'firstlaunch': 21,
 'flight': 22,
 'forpriv': 23,
 'fund': 24,
 'human': 25,
 'launch': 26,
 'man': 27,
 'million': 28,
 'offici': 29,
 'privat': 30,
 'prize': 31,
 'race': 32,
 'rocket': 33,
 'second': 34,
 'secondteam': 35,
 'set': 36,
 'space': 37,
 'spacecom': 38,
 'spaceflight': 39,
 'suborbit': 40,
 'team': 41,
 'toronto': 42,
 'acid': 43,
 'amino': 44,
 'better': 45,
 'block': 46,
 'build': 47,
 'chain': 48,
 'chemistri': 49,
 'compani': 50,
 'develop': 51,
 'found': 52,
 'grant': 53,
 'louisvil': 54,
 'method': 55,
 'peptid': 56,
 'produc': 57,
 'protein': 58,
 'research': 59,
 'short': 60,
 'studi': 61,
 'univers': 62,
 'win': 63,
 'alreadi': 64,
 'bare': 65,
 'blur': 66,
 'bring': 67,
 'chart': 68,
 'color': 69,
 'dawn': 70,
 'day': 71,
 'dri': 72,
 'endless': 73,
 'expect': 74,
 'figur': 75,
 'fitzpatrick': 76,
 'flame': 77,
 'forecast': 78,
 'help': 79,
 'know': 80,
 'lightn': 81,
 'map': 82,
 'mike': 83,
 'moist': 84,
 'pick': 85,
 'place': 86,
 'predict': 87,
 'roar': 88,
 'shift': 89,
 'start': 90,
 'strike': 91,
 'unit': 92,
 'wildfir': 93,
 'wind': 94,
 'adopt': 95,
 'agenc': 96,
 'aim': 97,
 'air': 98,
 'bovin': 99,
 'calif': 100,
 'california': 101,
 'cow': 102,
 'dairi': 103,
 'emiss': 104,
 'farmrel': 105,
 'first': 106,
 'friday': 107,
 'limit': 108,
 'manur': 109,
 'nation': 110,
 'pollut': 111,
 'reduc': 112,
 'rule': 113,
 'smog': 114,
 'smogfight': 115,
 'southern': 116,
 'varieti': 117,
 'went': 118,
 'also': 119,
 'appar': 120,
 'area': 121,
 'artist': 122,
 'audac': 123,
 'british': 124,
 'campaign': 125,
 'children': 126,
 'copyright': 127,
 'depart': 128,
 'dfe': 129,
 'download': 130,
 'educ': 131,
 'emi': 132,
 'end': 133,
 'feel': 134,
 'find': 135,
 'gener': 136,
 'got': 137,
 'gover': 138,
 'happen': 139,
 'hope': 140,
 'ignor': 141,
 'illeg': 142,
 'indoctrin': 143,
 'industri': 144,
 'inspir': 145,
 'intent': 146,
 'letter': 147,
 'littl': 148,
 'make': 149,
 'manifesto': 150,
 'music': 151,
 'musician': 152,
 'musicth': 153,
 'negoti': 154,
 'next': 155,
 'open': 156,
 'ostens': 157,
 'pedant': 158,
 'perhap': 159,
 'popular': 160,
 'recent': 161,
 'school': 162,
 'similar': 163,
 'skill': 164,
 'someth': 165,
 'suppos': 166,
 'thing': 167,
 'unfortun': 168,
 'use': 169,
 'variou': 170,
 'well': 171,
 'write': 172,
 'wrote': 173,
 '18yearold': 174,
 'accord': 175,
 'admit': 176,
 'antiviru': 177,
 'arrest': 178,
 'author': 179,
 'captur': 180,
 'cluley': 181,
 'confirm': 182,
 'consult': 183,
 'custodi': 184,
 'five': 185,
 'germani': 186,
 'graham': 187,
 'infect': 188,
 'isrespons': 189,
 'jaschan': 190,
 'least': 191,
 'led': 192,
 'loos': 193,
 'may': 194,
 'microsoft': 195,
 'month': 196,
 'netski': 197,
 'network': 198,
 'one': 199,
 'percent': 200,
 'polic': 201,
 'portscan': 202,
 'preced': 203,
 'program': 204,
 'publish': 205,
 'reward': 206,
 'roundup': 207,
 'said': 208,
 'sasser': 209,
 'selfconfess': 210,
 'senior': 211,
 'sixmonthviru': 212,
 'somethingexpert': 213,
 'sopho': 214,
 'staggeri': 215,
 'sven': 216,
 'taken': 217,
 'technolog': 218,
 'terror': 219,
 'therewer': 220,
 'theteenag': 221,
 'variant': 222,
 'viru': 223,
 'virus': 224,
 'war': 225,
 'wednesday': 226,
 'whosaid': 227,
 'worm': 228,
 'wormsass': 229,
 'base': 230,
 'bloom': 231,
 'clientdiscov': 232,
 'could': 233,
 'cours': 234,
 'direct': 235,
 'distribut': 236,
 'distributioni': 237,
 'encrypt': 238,
 'entir': 239,
 'file': 240,
 'filter': 241,
 'fingerprint': 242,
 'foaf': 243,
 'foaffil': 244,
 'foafkey': 245,
 'foafloaf': 246,
 'friend': 247,
 'gpgopenpgp': 248,
 'higher': 249,
 'ident': 250,
 'identit': 251,
 'includ': 252,
 'interest': 253,
 'key': 254,
 'keydistributionwhat': 255,
 'keyfingerpr': 256,
 'keyfingerprint': 257,
 'level': 258,
 'lot': 259,
 'mean': 260,
 'needto': 261,
 'new': 262,
 'pgp': 263,
 'popul': 264,
 'properti': 265,
 'simpl': 266,
 'social': 267,
 'socialnetwork': 268,
 'sourc': 269,
 'thi': 270,
 'think': 271,
 'though': 272,
 'weboftrust': 273,
 'whitelist': 274,
 'within': 275,
 'would': 276,
 'your': 277,
 'chief': 278,
 'email': 279,
 'fraud': 280,
 'phish': 281,
 'scam': 282,
 'squad': 283,
 'target': 284,
 'warn': 285,
 'wiltshir': 286,
 '36000': 287,
 '65m': 288,
 'card': 289,
 'dedic': 290,
 'estim': 291,
 'net': 292,
 'recov': 293,
 'save': 294,
 'stolen': 295,
 'two': 296,
 'year': 297,
 'angel': 298,
 'brcmo': 299,
 'broadcom': 300,
 'corp': 301,
 'current': 302,
 'format': 303,
 'group': 304,
 'highspe': 305,
 'inc': 306,
 'instrument': 307,
 'lo': 308,
 'propos': 309,
 'reuter': 310,
 'speed': 311,
 'standard': 312,
 'stmicroelectron': 313,
 'stmpa': 314,
 'texa': 315,
 'thursday': 316,
 'time': 317,
 'txnn': 318,
 'wireless': 319,
 'aaplo': 320,
 'appl': 321,
 'began': 322,
 'bundl': 323,
 'comput': 324,
 'creat': 325,
 'cut': 326,
 'design': 327,
 'discount': 328,
 'featur': 329,
 'final': 330,
 'flagship': 331,
 'graphic': 332,
 'let': 333,
 'motion': 334,
 'pro': 335,
 'realtim': 336,
 'ship': 337,
 'softwar': 338,
 'tuesday': 339,
 'unveil': 340,
 'user': 341,
 'video': 342,
 'videoedit': 343,
 'amsterdam': 344,
 'battleground': 345,
 'beat': 346,
 'digit': 347,
 'dutch': 348,
 'europ': 349,
 'free': 350,
 'latest': 351,
 'local': 352,
 'market': 353,
 'record': 354,
 'retail': 355,
 'servic': 356,
 'shop': 357,
 'song': 358,
 '100km': 359,
 'ant': 360,
 'australia': 361,
 'coloni': 362,
 'discov': 363,
 'giant': 364,
 'hit': 365,
 'insect': 366,
 'melbourn': 367,
 'speci': 368,
 'super': 369,
 'threaten': 370,
 'claim': 371,
 'collaps': 372,
 'dolphin': 373,
 'keep': 374,
 'pod': 375,
 'reli': 376,
 'scientist': 377,
 'socialit': 378,
 'achiev': 379,
 'adolesc': 380,
 'due': 381,
 'enorm': 382,
 'growth': 383,
 'massiv': 384,
 'monster': 385,
 'rex': 386,
 'size': 387,
 'spurt': 388,
 'teenag': 389,
 'tyrannosauru': 390,
 'beneath': 391,
 'billion': 392,
 'ganymed': 393,
 'ici': 394,
 'interior': 395,
 'irregular': 396,
 'jet': 397,
 'jupit': 398,
 'lab': 399,
 'largest': 400,
 'lump': 401,
 'lumpi': 402,
 'mass': 403,
 'moon': 404,
 'propuls': 405,
 'rock': 406,
 'shell': 407,
 'support': 408,
 'surfac': 409,
 'capabl': 410,
 'demonstr': 411,
 'draw': 412,
 'esa': 413,
 'european': 414,
 'express': 415,
 'futur': 416,
 'imag': 417,
 'interplanetari': 418,
 'joint': 419,
 'mar': 420,
 'mission': 421,
 'nasa': 422,
 'part': 423,
 'pave': 424,
 'pictur': 425,
 'relay': 426,
 'rover': 427,
 'way': 428,
 'although': 429,
 'begin': 430,
 'biolog': 431,
 'chemic': 432,
 'clue': 433,
 'content': 434,
 'cradl': 435,
 'debat': 436,
 'describ': 437,
 'evidenti': 438,
 'fossil': 439,
 'issu': 440,
 'layer': 441,
 'life': 442,
 'mcloughlin': 443,
 'nicola': 444,
 'oxford': 445,
 'sediment': 446,
 'spawn': 447,
 'spirit': 448,
 'stem': 449,
 'western': 450,
 'whether': 451,
 'ago': 452,
 'analyst': 453,
 'bruis': 454,
 'compar': 455,
 'earn': 456,
 'long': 457,
 'miss': 458,
 'per': 459,
 'rise': 460,
 'server': 461,
 'share': 462,
 'shot': 463,
 'storag': 464,
 'updat': 465,
 'biggest': 466,
 'even': 467,
 'headcount': 468,
 'hire': 469,
 'ibm': 470,
 'plan': 471,
 'sinc': 472,
 'code': 473,
 'craft': 474,
 'earli': 475,
 'get': 476,
 'glass': 477,
 'look': 478,
 'oper': 479,
 'provid': 480,
 'skin': 481,
 'still': 482,
 'sun': 483,
 'system': 484,
 'view': 485,
 'appli': 486,
 'chip': 487,
 'electr': 488,
 'fault': 489,
 'fuse': 490,
 'heal': 491,
 'identifi': 492,
 'repair': 493,
 'someday': 494,
 'bid': 495,
 'bill': 496,
 'case': 497,
 'deni': 498,
 'elig': 499,
 'everyday': 500,
 'googl': 501,
 'ipo': 502,
 'minimum': 503,
 'particip': 504,
 'peopl': 505,
 'point': 506,
 'process': 507,
 'public': 508,
 'stranglehold': 509,
 'street': 510,
 'underwrit': 511,
 'usual': 512,
 'wall': 513,
 'annoy': 514,
 'attitud': 515,
 'broker': 516,
 'charl': 517,
 'decad': 518,
 'francisco': 519,
 'iconoclast': 520,
 'liedtk': 521,
 'low': 522,
 'michael': 523,
 'price': 524,
 'rival': 525,
 'san': 526,
 'sch': 527,
 'schwab': 528,
 'shoe': 529,
 'stock': 530,
 'stone': 531,
 'tabl': 532,
 'tri': 533,
 'turn': 534,
 'wingtip': 535,
 'compon': 536,
 'cyber': 537,
 'fail': 538,
 'grid': 539,
 'movement': 540,
 'news': 541,
 'power': 542,
 'reach': 543,
 'secur': 544,
 'sluggish': 545,
 'vulner': 546,
 '826': 547,
 'giddi': 548,
 'gold': 549,
 'individu': 550,
 'medal': 551,
 'medley': 552,
 'minut': 553,
 'phelp': 554,
 'touch': 555,
 'world': 556,
 'arguabl': 557,
 'best': 558,
 'bicep': 559,
 'bodi': 560,
 'choos': 561,
 'cornerback': 562,
 'deion': 563,
 'easi': 564,
 'fat': 565,
 'field': 566,
 'finess': 567,
 'footbal': 568,
 'foxborough': 569,
 'game': 570,
 'hardli': 571,
 'huge': 572,
 'impli': 573,
 'lack': 574,
 'law': 575,
 'much': 576,
 'ounc': 577,
 'physic': 578,
 'play': 579,
 'ridicul': 580,
 'sander': 581,
 'see': 582,
 'shut': 583,
 'side': 584,
 'soften': 585,
 'tougher': 586,
 'upper': 587,
 'adjust': 588,
 'appear': 589,
 'care': 590,
 'catcher': 591,
 'climb': 592,
 'continu': 593,
 'dwindl': 594,
 'enter': 595,
 'highli': 596,
 'jason': 597,
 'kelli': 598,
 'like': 599,
 'major': 600,
 'monitor': 601,
 'pawtucket': 602,
 'plate': 603,
 'readi': 604,
 'red': 605,
 'remain': 606,
 'seen': 607,
 'shoppach': 608,
 'sox': 609,
 'toward': 610,
 'tripl': 611,
 'uncertain': 612,
 'varitek': 613,
 'week': 614,
 'attend': 615,
 'babi': 616,
 'boy': 617,
 'dangelo': 618,
 'david': 619,
 'famili': 620,
 'fenway': 621,
 'good': 622,
 'home': 623,
 'imagin': 624,
 'last': 625,
 'mighti': 626,
 'morn': 627,
 'night': 628,
 'old': 629,
 'ortiz': 630,
 'park': 631,
 'rest': 632,
 'sleep': 633,
 'son': 634,
 'spent': 635,
 'sure': 636,
 'yesterday': 637,
 'belichick': 638,
 'bryant': 639,
 'caught': 640,
 'cha': 641,
 'decis': 642,
 'easier': 643,
 'eye': 644,
 'gessner': 645,
 'jen': 646,
 'noth': 647,
 'patten': 648,
 'quot': 649,
 'receiv': 650,
 'ricki': 651,
 'central': 652,
 'charg': 653,
 'cleveland': 654,
 'hafner': 655,
 'indian': 656,
 'lead': 657,
 'martinez': 658,
 'minnesota': 659,
 'mount': 660,
 'pull': 661,
 'run': 662,
 'saturday': 663,
 'travi': 664,
 'twin': 665,
 'victor': 666,
 'canadian': 667,
 'citi': 668,
 'confront': 669,
 'constabl': 670,
 'defend': 671,
 'demand': 672,
 'die': 673,
 'involv': 674,
 'offic': 675,
 'press': 676,
 'resign': 677,
 'sister': 678,
 'slam': 679,
 'vancouv': 680,
 'violent': 681,
 '50m': 682,
 'affair': 683,
 'aid': 684,
 'associ': 685,
 'cash': 686,
 'decid': 687,
 'extramarit': 688,
 'gay': 689,
 'gov': 690,
 'governor': 691,
 'harass': 692,
 'jame': 693,
 'mcgreevey': 694,
 'push': 695,
 'settlement': 696,
 'sexual': 697,
 'sought': 698,
 'told': 699,
 'armor': 700,
 'back': 701,
 'ceasefir': 702,
 'echo': 703,
 'explos': 704,
 'fight': 705,
 'gunfir': 706,
 'holi': 707,
 'intend': 708,
 'iraq': 709,
 'najaf': 710,
 'rattl': 711,
 'roll': 712,
 'sunday': 713,
 'tank': 714,
 'temporari': 715,
 'throughout': 716,
 'troop': 717,
 'vehicl': 718,
 'breath': 719,
 'celebr': 720,
 'cure': 721,
 'frail': 722,
 'franc': 723,
 'french': 724,
 'gasp': 725,
 'heavili': 726,
 'homili': 727,
 'hundr': 728,
 'john': 729,
 'lourd': 730,
 'mani': 731,
 'mari': 732,
 'miracul': 733,
 'openair': 734,
 'paul': 735,
 'pilgrim': 736,
 'polish': 737,
 'pope': 738,
 'sever': 739,
 'shrine': 740,
 'struggl': 741,
 'thousand': 742,
 'virgin': 743,
 'wheelchair': 744,
 'chavez': 745,
 'defeat': 746,
 'govern': 747,
 'oil': 748,
 'possibl': 749,
 'prepar': 750,
 'recal': 751,
 'turmoil': 752,
 'venezuela': 753,
 'vote': 754,
 'act': 755,
 'activ': 756,
 'call': 757,
 'duti': 758,
 'employ': 759,
 'guard': 760,
 'job': 761,
 'preserv': 762,
 'protect': 763,
 'provis': 764,
 'reemploy': 765,
 'reserv': 766,
 'right': 767,
 'strengthen': 768,
 'uniform': 769,
 'userra': 770,
 'anywher': 771,
 'attack': 772,
 'dare': 773,
 'iran': 774,
 'iranian': 775,
 'israel': 776,
 'militari': 777,
 'missil': 778,
 'report': 779,
 'state': 780,
 'tehran': 781,
 'afghan': 782,
 'afghanistan': 783,
 'airplan': 784,
 'armi': 785,
 'calm': 786,
 'capit': 787,
 'deadli': 788,
 'dispatch': 789,
 'far': 790,
 'fli': 791,
 'interven': 792,
 'kabul': 793,
 'nato': 794,
 'outbreak': 795,
 'retak': 796,
 'violenc': 797,
 'warlord': 798,
 'west': 799,
 'arizona': 800,
 'dback': 801,
 'diamondback': 802,
 'fourhitt': 803,
 'inning': 804,
 'johnson': 805,
 'lose': 806,
 'met': 807,
 'ninegam': 808,
 'ninth': 809,
 'randi': 810,
 'slide': 811,
 'steve': 812,
 'streak': 813,
 'took': 814,
 'trachsel': 815,
 'york': 816,
 'adult': 817,
 'amongstyleconsci': 818,
 'apparel': 819,
 'backtoschool': 820,
 'buyer': 821,
 'couldb': 822,
 'fall': 823,
 'fashion': 824,
 'grade': 825,
 'sell': 826,
 'student': 827,
 'teen': 828,
 'theirbacktoschool': 829,
 'tighterhold': 830,
 'tough': 831,
 'vie': 832,
 'wallet': 833,
 'young': 834,
 'afterthought': 835,
 'amid': 836,
 'bush': 837,
 'charley': 838,
 'coastal': 839,
 'earthquak': 840,
 'fire': 841,
 'flood': 842,
 'hurrican': 843,
 'made': 844,
 'polit': 845,
 'postdisast': 846,
 'presid': 847,
 'scene': 848,
 'sort': 849,
 'storm': 850,
 'struck': 851,
 'three': 852,
 'tour': 853,
 'visit': 854,
 'wreckag': 855,
 'cent': 856,
 'china': 857,
 'chines': 858,
 'custom': 859,
 'fell': 860,
 'ftcom': 861,
 'impos': 862,
 'internet': 863,
 'messag': 864,
 'mobil': 865,
 'multimedia': 866,
 'oneyear': 867,
 'phone': 868,
 'portal': 869,
 'sent': 870,
 'sohucom': 871,
 'spam': 872,
 'suspens': 873,
 'uslist': 874,
 'anaheim': 875,
 'boston': 876,
 'darin': 877,
 'detroit': 878,
 'doubl': 879,
 'eighth': 880,
 'erstad': 881,
 'goahead': 882,
 'lift': 883,
 'percentag': 884,
 'tiger': 885,
 'victori': 886,
 'wildcard': 887,
 'atlanta': 888,
 'brave': 889,
 'cardin': 890,
 'drew': 891,
 'injuri': 892,
 'lineup': 893,
 'loui': 894,
 'outfield': 895,
 'quadricep': 896,
 'sore': 897,
 'caraca': 898,
 'elector': 899,
 'extend': 900,
 'histor': 901,
 'hugo': 902,
 'leftw': 903,
 'number': 904,
 'poll': 905,
 'prolong': 906,
 'referendum': 907,
 'venezuelan': 908,
 'competit': 909,
 'consum': 910,
 'countri': 911,
 'dell': 912,
 'dello': 913,
 'exit': 914,
 'hong': 915,
 'kong': 916,
 'left': 917,
 'lowend': 918,
 'maker': 919,
 'monday': 920,
 'overal': 921,
 'segment': 922,
 'stiff': 923,
 'accus': 924,
 'beij': 925,
 'chineseamerican': 926,
 'espionag': 927,
 'media': 928,
 'soon': 929,
 'spi': 930,
 'taiwan': 931,
 'trial': 932,
 'anoth': 933,
 'championship': 934,
 'nonfactor': 935,
 'player': 936,
 'rank': 937,
 'triumph': 938,
 'wood': 939,
 'afp': 940,
 'alaska': 941,
 'deploy': 942,
 'enhanc': 943,
 'f15e': 944,
 'fighter': 945,
 'firepow': 946,
 'forc': 947,
 'korea': 948,
 'korean': 949,
 'peninsula': 950,
 'south': 951,
 'squadron': 952,
 'batter': 953,
 'host': 954,
 'leagu': 955,
 'curfew': 956,
 'dissid': 957,
 'eas': 958,
 'emerg': 959,
 'follow': 960,
 'indefinit': 961,
 'maldiv': 962,
 'parliament': 963,
 'put': 964,
 'resid': 965,
 'restiv': 966,
 'riot': 967,
 'round': 968,
 'session': 969,
 'busi': 970,
 'ceski': 971,
 'czech': 972,
 'disentagl': 973,
 'fixedlin': 974,
 'thedealcom': 975,
 'vodafon': 976,
 'want': 977,
 '4wk': 978,
 'briefli': 979,
 'data': 980,
 'dip': 981,
 'dollar': 982,
 'economi': 983,
 'euro': 984,
 'fan': 985,
 'fourweek': 986,
 'health': 987,
 'london': 988,
 'profittak': 989,
 'slightli': 990,
 'steep': 991,
 'weak': 992,
 'worri': 993,
 'kaleko': 994,
 'kept': 995,
 'older': 996,
 'problem': 997,
 'promot': 998,
 'realiz': 999,
 ...}

Mapping of tokens

In [ ]:
dictionary.token2id['disappoint'], dictionary.token2id['california']

(0, 101)

Upon creation of a dictionary that maps words to integers (and vice versa), we can transform our bag of words. Each document will be a list of tuples that contain token indices and frequencies.

In [ ]:
corpus = [dictionary.doc2bow(d) for d in bow]
corpus[0]

[(0, 1),
 (1, 1),
 (2, 1),
 (3, 1),
 (4, 1),
 (5, 1),
 (6, 1),
 (7, 1),
 (8, 1),
 (9, 1),
 (10, 1),
 (11, 2),
 (12, 1),
 (13, 1),
 (14, 1)]

###### TFIDF

Sometimes term frequencies can be misleading. Just like the same reason we remove stop words, words that occur a lot across the whole corpus may not be informative. On the other hand, a word that shows up a lot in only a small portion instead of all can provide valuable informaiton on the contents of these texts.

One way to resolve this potential problem is called term frequency-inverse document frequency (TFIDF), which is a product of TF and IDF. A common weighting scheme is $TFIDF(t,d, D) = freq_{t,d}\times log_2~\dfrac{N_D}{N_t}$, where $N_D$ is the number of documents; $N_t$ is the number of documents that contain the term $t$. See [here](https://en.wikipedia.org/wiki/Tf%E2%80%93idf#Term_frequency) for more details.

We can try this on our data with [`gensim.models.tfidfmodel`](https://radimrehurek.com/gensim/models/tfidfmodel.html):

In [ ]:
from gensim.models import TfidfModel
model = TfidfModel(corpus)

Apply the model on one document

In [ ]:
model[corpus[0]]

[(0, 0.23464966537701473),
 (1, 0.21340476186532015),
 (2, 0.16098999782417597),
 (3, 0.17617388045540608),
 (4, 0.3380922768382177),
 (5, 0.35558360355081436),
 (6, 0.25022339107653035),
 (7, 0.2521409920896115),
 (8, 0.22971412643239364),
 (9, 0.1150431833134092),
 (10, 0.38548522406671576),
 (11, 0.31781564552907887),
 (12, 0.3081906563223163),
 (13, 0.17230810874356683),
 (14, 0.18769468048518562)]

---

#### Topic Modeling

##### Latent Dirichet Allocation (LDA)

A very commonly used dimensionality reduction technique family is called ___topic modeling___. It assumes that each document is a mixture of topics, where each topic is a mixture of terms. One of the most successful algorithms is [___latent Dirichlet allocation___](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation) (LDA), whose corresponding paper is:
> Blei, D. M., Ng, A. Y., & Jordan, M. I. (2003). Latent dirichlet allocation. Journal of machine Learning research, 3(Jan), 993-1022.

LDA is a generative model that does the reverse engineerging of document generation. It can be represented as a probablistic graphical model:
![lda](https://upload.wikimedia.org/wikipedia/commons/4/4d/Smoothed_LDA.png)

The generative process can be described as follows:
- For each topic $k$, sample a multinomial distribution $\phi_k$ over words from the Dirichlet prior with parameter $\beta$
- For each document $m$, sample a multinomial distribution $\theta_m$ over topics from the Dirichlet prior with parameter $\alpha$
    - For each word $n$ in $m$:
        - Sample a topic $z_{m,n}$ from the correponding topic distribution parameterized by $\theta_m$
        - Sample a word $w_{m,n}$ from the correponding topic $z_{m,n}$'s word distribution parameterized by $\phi_{z_{m,n}}$

##### Parameters in LDA

Generally, we need to control two hyperparamters of a LDA model:
- Topic-word Dirichlet prior $\beta$
- Document-topic Dirichlet prior $\alpha$

The selection of these parameters are application dependent. Heuristically, people will choose $\alpha=\dfrac{50}{K}$ and $\beta=0.01$, as described in

> Griffiths, T. L., and Steyvers, M. 2004. “Finding Scientific Topics,” Proceedings of the National Academy of Sciences (101:Supplement 1), National Academy of Sciences, pp. 5228–5235.

It is also possible to infer these two hyperparameters given the data.

The selection of $K$ totally depends on the context. It is also possible to select a topic number based on quantitative measures of topic modeling quality, but this is beyond the scope of this tutorial.

For our toy sample set, we will just select $K=4$ because there are 4 labels:

In [ ]:
df.class_name.unique()

array(['Business', 'Sci/Tech', 'Sports', 'World'], dtype=object)

##### Run LDA!

Thanks to the convenient APIs by `gensim`, we can easily run [LDA in Python](https://radimrehurek.com/gensim/models/ldamodel.html):

In [ ]:
from gensim.models import LdaModel
lda = LdaModel(corpus, num_topics=4, id2word=dictionary, passes=10,
               minimum_probability=0)

##### Analysis on LDA results

Let's take a look at the output of LDA. First, we can check if the topics make sense

In [ ]:
for _, topic_str in lda.show_topics():
    print(topic_str)
    print('------------'*10)

0.008*"win" + 0.007*"game" + 0.006*"first" + 0.006*"team" + 0.005*"season" + 0.005*"last" + 0.004*"two" + 0.004*"final" + 0.004*"one" + 0.004*"night"
------------------------------------------------------------------------------------------------------------------------
0.010*"said" + 0.009*"reuter" + 0.007*"kill" + 0.007*"oil" + 0.006*"presid" + 0.006*"iraq" + 0.005*"govern" + 0.005*"afp" + 0.005*"offici" + 0.005*"say"
------------------------------------------------------------------------------------------------------------------------
0.012*"new" + 0.007*"microsoft" + 0.006*"search" + 0.005*"googl" + 0.005*"quot" + 0.004*"announc" + 0.004*"intel" + 0.004*"linux" + 0.004*"secur" + 0.003*"softwar"
------------------------------------------------------------------------------------------------------------------------
0.010*"said" + 0.010*"compani" + 0.008*"new" + 0.007*"inc" + 0.006*"reuter" + 0.006*"year" + 0.005*"million" + 0.005*"share" + 0.005*"servic" + 0.005*"sale"
------------------------------------------------------------------------------------------------------------------------

While we probably cannot say the topics are perfect, they are okay. We can interpret the topics as: business, sports, world, and sci/tech.

For each document, we can check their topic distributions:

In [ ]:
i = 1000
lda.get_document_topics(corpus[i])

[(0, 0.012327542), (1, 0.16224293), (2, 0.012031073), (3, 0.8133985)]

We can see that topic 0, which is interpreted "business" topics dominate this document. We can check to see if this makes sense:

In [ ]:
df.loc[i]

class_index                                                    3
class_name                                              Business
content        Albertsons #39; 2Q Profit Falls 36 Percent. Pe...
Name: 1000, dtype: object

In fact, LDA can be used in many situtaions, such as information retrieval, document clustering and labeling, and even for images! Here we just mention the simplest use case

---

#### Conclusion

In this tutorial, we went through a simple procedure, from preprocessing of raw texts, to modeling topics in the resulting bag of words corpus. A lot of terms are used, such as ___stop words___, ___bag of words___, ___stemming___, etc. However, these are only a small part of text analytics. There are a lot more to explore. Below I list some materials on text analytics in Python that may be useful:

- [Gensim tutorial](https://radimrehurek.com/gensim/tutorial.html)
- [NLTK book](http://www.nltk.org/book/)
- [Coursera text mining course](https://www.coursera.org/learn/python-text-mining)
- [TextBlob](https://textblob.readthedocs.io/en/dev/quickstart.html) (A package not tutorial)