In [74]:
import pandas as pd
import numpy as np

In [76]:
df = pd.read_csv("marvel-wikia-data.csv")
df.head()

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,Year
0,1678,Spider-Man (Peter Parker),\/Spider-Man_(Peter_Parker),Secret Identity,Good Characters,Hazel Eyes,Brown Hair,Male Characters,NaN,Living Characters,4043.0,Aug-62,1962.0
1,7139,Captain America (Steven Rogers),\/Captain_America_(Steven_Rogers),Public Identity,Good Characters,Blue Eyes,White Hair,Male Characters,NaN,Living Characters,3360.0,Mar-41,1941.0
2,64786,"Wolverine (James \""Logan\"" Howlett)",\/Wolverine_(James_%22Logan%22_Howlett),Public Identity,Neutral Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,3061.0,Oct-74,1974.0
3,1868,"Iron Man (Anthony \""Tony\"" Stark)",\/Iron_Man_(Anthony_%22Tony%22_Stark),Public Identity,Good Characters,Blue Eyes,Black Hair,Male Characters,NaN,Living Characters,2961.0,Mar-63,1963.0
4,2460,Thor (Thor Odinson),\/Thor_(Thor_Odinson),No Dual Identity,Good Characters,Blue Eyes,Blond Hair,Male Characters,NaN,Living Characters,2258.0,Nov-50,1950.0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16376 entries, 0 to 16375
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   page_id           16376 non-null  int64
 1   name              16376 non-null  object
 2   urlslug           16376 non-null  object
 3   ID                12606 non-null  object
 4   ALIGN             13564 non-null  object
 5   EYE               6609 non-null   object
 6   HAIR              12112 non-null  object
 7   SEX               15522 non-null  object
 8   GSM               90 non-null     object
 9   ALIVE             16373 non-null  object
 10  APPEARANCES       15280 non-null  float64
 11  FIRST APPEARANCE  15561 non-null  object
 12  Year              15561 non-null  float64
dtypes: float64(2), int64(1), object(10)
memory usage: 1.6+ MB

## First Impression ##

This dataset compiles all Marvel figures (played by actors) in the universe, provided with URL slug name for convenient Wikipedia search. 

Viewers presumably have impression on good characters, who are determined to save the world, bear prolonged imprints toward children, whereas Neutral and bad characters are often considered to be "evil".

However, there exists an imbalance in terms of genders, where male figures have tendency to shine other than female ones such as Carol Danvers.

Some of basic identities of a Marvel figure: Name, ID, Align (Heroes - Neutral - Villians), Eye, Hair, Sex, GSM, Alive, Appearances, Year - First Appearances

## Data Exploration ##

#### Involving these following steps: ####

<li> Measures of central tendency (mean, median, and mode) and dispersion (standard deviation and range) to understand the distribution of your data. <li> Check for missing values to identify gaps in your data that might require filling. 
<li> Look at the structure of your data, including the number of columns and rows.

In [97]:
df.shape

(16376, 13)

In [83]:
df["APPEARANCES"].mean()

17.033376963350786

In [85]:
df["APPEARANCES"].median()

3.0

In [87]:
df["HAIR"].mode() 
#The frequency of black hair outweights characters whose hair are stylish (blond, white,...)

0    Black Hair
Name: HAIR, dtype: object

#### This dataset contains some of invalid results (NaN values) ####

In [95]:
missing_cols = ["GSM", "APPEARANCES", "FIRST APPEARANCE"]

df[df[missing_cols].isnull().all(axis = 1)]

,page_id,name,urlslug,ID,ALIGN,EYE,HAIR,SEX,GSM,ALIVE,APPEARANCES,FIRST APPEARANCE,Year
16176,511845,Aberham (Earth-616),\/Aberham_(Earth-616),Secret Identity,Good Characters,Blue Eyes,Blond Hair,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16177,53473,Ace (Pilot) (Earth-616),\/Ace_(Pilot)_(Earth-616),NaN,NaN,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16178,388119,Alan Brialige (Earth-616),\/Alan_Brialige_(Earth-616),NaN,Bad Characters,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16179,18503,Aldo Moomjay (Earth-616),\/Aldo_Moomjay_(Earth-616),NaN,NaN,NaN,NaN,NaN,NaN,Living Characters,NaN,NaN,NaN
16180,65713,Alfred Gray (Earth-616),\/Alfred_Gray_(Earth-616),NaN,Neutral Characters,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16371,657508,Ru'ach (Earth-616),\/Ru%27ach_(Earth-616),No Dual Identity,Bad Characters,Green Eyes,No Hair,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16372,665474,Thane (Thanos' son) (Earth-616),\/Thane_(Thanos%27_son)_(Earth-616),No Dual Identity,Good Characters,Blue Eyes,Bald,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16373,695217,Tinkerer (Skrull) (Earth-616),\/Tinkerer_(Skrull)_(Earth-616),Secret Identity,Bad Characters,Black Eyes,Bald,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16374,708811,TK421 (Spiderling) (Earth-616),\/TK421_(Spiderling)_(Earth-616),Secret Identity,Neutral Characters,NaN,NaN,Male Characters,NaN,Living Characters,NaN,NaN,NaN
16375,673702,Yologarch (Earth-616),\/Yologarch_(Earth-616),NaN,Bad Characters,NaN,NaN,NaN,NaN,Living Characters,NaN,NaN,NaN

### Descriptive Statistics ###

In [92]:
df.describe()

             page_id   APPEARANCES          Year
count   16376.000000  15280.000000  15561.000000
mean   300232.082377     17.033377   1984.951803
std    253460.403399     96.372959     19.663571
min      1025.000000      1.000000   1939.000000
25%     28309.500000      1.000000   1974.000000
50%    282578.000000      3.000000   1990.000000
75%    509077.000000      8.000000   2000.000000
max    755278.000000   4043.000000   2013.000000