In [1]:
import pandas as pd

In [7]:
df = pd.DataFrame({
   'name': ['John', 'Emily', 'John', 'Jane', 'John'],
   'age': [25, 28, 25, 30, 25],
   'salary': [50000, 60000, 50000, 70000, 50000]
})

In [15]:
#Check for duplicated values
duplicates = df.duplicated()
df[duplicates]

   name  age  salary
2  John   25   50000
4  John   25   50000

In [19]:
#Drop duplicated values
df = df.drop_duplicates()
df

    name  age  salary
0   John   25   50000
1  Emily   28   60000
3   Jane   30   70000