In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("movies.csv")
df.head(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,(2021),"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,(2006–2013),"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN
8,Never Have I Ever,(2020– ),\nComedy,7.9,\nThe complicated life of a modern-day first g...,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN
9,Virgin River,(2019– ),"\nDrama, Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...",\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN

In [7]:
#View the properties of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   object
 1   YEAR      9355 non-null   object
 2   GENRE     9919 non-null   object
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   object
 5   STARS     9999 non-null   object
 6   VOTES     8179 non-null   object
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

In [13]:
df.select_dtypes(include = "float64").columns

Index(['RATING', 'RunTime'], dtype='object')

In [15]:
from sklearn.impute import SimpleImputer

### There are four primary strategies to fill in NaN values: mean, median, most_frequent, constant

| Strategy        | Applies To                | Description                                                   | Common Use Case                                         |
|----------------|---------------------------|---------------------------------------------------------------|---------------------------------------------------------|
| `mean`         | Numerical                 | Fills missing values with the **mean** of the column           | When numerical data is roughly **normally distributed** |
| `median`       | Numerical (robust to outliers) | Fills missing values with the **median** of the column    | When data contains **outliers**                         |
| `most_frequent`| Numerical & Categorical   | Fills missing values with the **most frequent value** (mode)   | For **categorical** features or simple numerics         |
| `constant`     | Numerical & Categorical   | Fills missing values with a **constant** (set via `fill_value`) | To use placeholders like `'Unknown'`, `0`, or `-999`    |

In [25]:
si = SimpleImputer(strategy = "mean")
ar = si.fit_transform((df[['RATING', 'RunTime']]))

In [39]:
#Displaying the filtered categories by displaying as DataFrame with the index column selected with dtypes - float64
new_df = pd.DataFrame(ar, columns = df.select_dtypes(include = "float64").columns)
new_df

        RATING     RunTime
0     6.100000  121.000000
1     5.000000   25.000000
2     8.200000   44.000000
3     9.200000   23.000000
4     6.921176   68.688539
...        ...         ...
9994  6.921176   68.688539
9995  6.921176   68.688539
9996  6.921176   68.688539
9997  6.921176   68.688539
9998  6.921176   68.688539

[9999 rows x 2 columns]